defaults.url=https://sentry.io/
defaults.org=fresnel-un
defaults.project=react
# DSN: https://79022c5722addfd7e6eb180ddd268469@o4510896900276224.ingest.us.sentry.io/4510897006182400

# Auth token is read from SENTRY_AUTH_TOKEN environment variable
